# Generated by Django 4.2.1 on 2023-06-11 23:56

import core.db
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_remove_event_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.db.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("heading", models.CharField(max_length=255, unique=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event Type",
                "verbose_name_plural": "Event Types",
                "db_table": "event_types",
                "ordering": ["heading"],
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.CreateModel(
            name="EventV2",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventtype",
                    ),
                ),
            ],
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="EventAnnouncement",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.db.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Announcement",
                "verbose_name_plural": "Event Announcements",
                "db_table": "event_announcements",
                "ordering": ["-created_at"],
            },
        ),
    ]
