# Generated by Django 4.2.1 on 2023-06-11 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventtype_alter_event_options_eventv2_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventV2",
        ),
    ]
