# Generated by Django 4.2.1 on 2023-06-15 00:43

import core.db
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0007_alter_event_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={
                "ordering": ["-create_at"],
                "verbose_name": "Event Type",
                "verbose_name_plural": "Event Types",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.eventtype",
            ),
        ),
        migrations.AlterField(
            model_name="eventannouncement",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="events.event",
            ),
        ),
        migrations.CreateModel(
            name="EventAlertPreference",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.db.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_types",
                    models.ManyToManyField(
                        related_name="event_alerts", to="events.eventtype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Alert Preference",
                "verbose_name_plural": "Event Alert Preferences",
                "db_table": "event_alert_preferences",
                "ordering": ["-created_at"],
            },
        ),
    ]
