# Generated by Django 4.2.1 on 2023-06-16 01:26

import core.db
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_userfollow_unique_user_follower"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0008_alter_eventtype_options_alter_event_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventalertpreference",
            name="all_events",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventalertpreference",
            name="user_follow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_alerts",
                to="users.userfollow",
            ),
        ),
        migrations.CreateModel(
            name="EventFollower",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.db.generate_uuid,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_followers",
                        to="events.eventalertpreference",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="events.event",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Follower",
                "verbose_name_plural": "Event Followers",
                "db_table": "event_followers",
                "ordering": ["created_at"],
            },
        ),
    ]
