# Generated by Django 4.2.1 on 2023-06-16 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_eventalertpreference_all_events_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventalertpreference",
            name="event_types",
            field=models.ManyToManyField(
                blank=True, related_name="event_alerts", to="events.eventtype"
            ),
        ),
        migrations.AlterField(
            model_name="eventfollower",
            name="alert_preference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_followers",
                to="events.eventalertpreference",
            ),
        ),
    ]
