# Generated by Django 4.2.1 on 2023-06-16 01:44

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_alter_eventalertpreference_event_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.ForeignKey(
                default=events.models.EventType.default_event_type,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="events",
                to="events.eventtype",
            ),
        ),
    ]
