# Generated by Django 4.2.1 on 2023-07-10 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_alter_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="resource_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
