# Generated by Django 4.2.1 on 2023-07-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_event_resource_url_event_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
