# Generated by Django 4.2.1 on 2023-06-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userfollow_unique_user_follower"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfollow",
            name="unique_user_follower",
        ),
        migrations.AddConstraint(
            model_name="userfollow",
            constraint=models.UniqueConstraint(
                fields=("user", "follower"),
                name="unique_user_follower",
                violation_error_message="You are already following this user",
            ),
        ),
    ]
