# Generated by Django 4.2.1 on 2023-06-15 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_userfollow_unique_user_follower_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfollow",
            name="unique_user_follower",
        ),
    ]
