# Generated by Django 4.2.1 on 2023-07-14 22:24

import core.db
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_userfollow_unique_user_follower"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.db.generate_uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "2c56505a-c12c-46b3-bcfe-b9954965751d",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images"
                    ),
                ),
            ],
        ),
    ]
