# Generated by Django 4.2.1 on 2023-07-14 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0009_rename_2c56505a_c12c_46b3_bcfe_b9954965751d_account_profile_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "account", "verbose_name_plural": "accounts"},
        ),
        migrations.AlterModelTable(
            name="account",
            table="accounts",
        ),
    ]
