# Generated by Django 4.2.1 on 2023-07-14 22:49

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account",
            field=models.OneToOneField(
                blank=True,
                default=django.db.models.query.QuerySet.create,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="users.account",
            ),
        ),
    ]
